# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://github.com/auvious/CocoaPodSpecs.git'
source 'https://cdn.cocoapods.org/'

target 'SimpleConference' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleConference
  pod 'AuviousSDK', '1.2.0-beta.4'
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'

end
